DEFINE
	MEASURE 'public space_flights'[Total Missions] = COUNT('public space_flights'[index])
	MEASURE 'public space_flights'[Mission Succes Rate] = VAR grand_total =
		CALCULATE(
			[Total Missions],
			ALL('public space_flights'[MissionStatus])
		)
		VAR part_total =
		CALCULATE(
			[Total Missions],
			'public space_flights'[MissionStatus] = "SUCCESS"
		)
		VAR successrate = DIVIDE(
			part_total,
			grand_total
		)

		RETURN
			IF(
				successrate <> BLANK(),
				IF(
					AND(
						[Total Missions] < 3,
						successrate = 1
					),
					"not enough data",
					successrate
				),
				"not yet successful"
			)
	MEASURE 'public space_flights'[Total Revenue] = VAR revenue = SUM('public space_flights'[Price])
		RETURN
			revenue
	MEASURE 'public space_flights'[Company Choice] = IF(
			ISFILTERED(companies[Company]),
			SELECTEDVALUE(
				companies[Company],
				"Multiple Companies"
			),
			""
		)
	MEASURE 'public space_flights'[Mission price] = VAR price = SUM('public space_flights'[Price])
		RETURN
			price
	MEASURE 'public space_flights'[Mission priced] = IF(
			[Total Revenue] <> BLANK(),
			[Total Revenue],
			"No data"
		)
	MEASURE 'public space_flights'[MTD] = CALCULATE(
			[Total Missions],
			DATESMTD(date_table[Date])
		)
	MEASURE 'public space_flights'[unicode] = UNICHAR(9776)

EVALUATE
	SUMMARIZECOLUMNS(
		"Total Missions", 'public space_flights'[Total Missions],
		"Mission Succes Rate", 'public space_flights'[Mission Succes Rate],
		"Total Revenue", 'public space_flights'[Total Revenue],
		"Company Choice", 'public space_flights'[Company Choice],
		"Mission price", 'public space_flights'[Mission price],
		"Mission priced", 'public space_flights'[Mission priced],
		"MTD", 'public space_flights'[MTD],
		"unicode", 'public space_flights'[unicode]
	)