DEFINE
	MEASURE 'space missions'[Total Missions] = COUNT('space missions'[index])
	MEASURE 'space missions'[Mission Succes Rate] = VAR grand_total =
		CALCULATE(
			[Total Missions],
			ALL('space missions'[MissionStatus])
		)
		VAR part_total =
		CALCULATE(
			[Total Missions],
			'space missions'[MissionStatus] = "SUCCESS"
		)
		VAR successrate = DIVIDE(
			part_total,
			grand_total
		)

		RETURN
			IF(
				successrate <> BLANK(),
				IF(
					AND(
						[Total Missions] < 3,
						successrate = 1
					),
					"not enough data",
					successrate
				),
				"not yet successful"
			)
	MEASURE 'space missions'[Total Revenue] = VAR revenue = SUM('space missions'[Price])
		RETURN
			revenue
	MEASURE 'space missions'[Company Choice] = IF(
			ISFILTERED(companies[Company]),
			SELECTEDVALUE(
				companies[Company],
				"Multiple Companies"
			),
			""
		)
	MEASURE 'space missions'[Mission price] = VAR price = SUM('space missions'[Price])
		RETURN
			price
	MEASURE 'space missions'[Mission priced] = IF(
			[Total Revenue] <> BLANK(),
			[Total Revenue],
			"No data"
		)
	MEASURE 'space missions'[MTD] = CALCULATE(
			[Total Missions],
			DATESMTD(datetable[Date])
		)
	MEASURE 'space missions'[unicode] = UNICHAR(9776)

EVALUATE
	SUMMARIZECOLUMNS(
		"Total Missions", 'space missions'[Total Missions],
		"Mission Succes Rate", 'space missions'[Mission Succes Rate],
		"Total Revenue", 'space missions'[Total Revenue],
		"Company Choice", 'space missions'[Company Choice],
		"Mission price", 'space missions'[Mission price],
		"Mission priced", 'space missions'[Mission priced],
		"MTD", 'space missions'[MTD],
		"unicode", 'space missions'[unicode]
	)