DEFINE
    MEASURE 'measuretable'[title_year] = "in " & SELECTEDVALUE(datetable[Jaar]
, IF(
    ISFILTERED(datetable[jaar])
    ,CONCATENATEX(
    VALUES(datetable[Jaar])
    ,datetable[Jaar]
    ,", "
    , datetable[Jaar]
    ,ASC
    )
    , "all years"
))

    MEASURE 'measuretable'[selected_filters] = 
	VAR yearr = 
	IF(
		ISFILTERED(datetable[Jaar])
		, "Year selected: " & CONCATENATEX(VALUES(datetable[Jaar]), datetable[Jaar], ", ", datetable[Jaar], ASC)
		, "All years"
	)
	
	VAR company = 
	IF(
		ISFILTERED(companies[Company])
		, "Companies selected: " & CONCATENATEX(VALUES(companies[Company]), companies[Company], ", ", companies[Company], ASC)
		, "All companies"
	)
	
	VAR rocket = 
	IF(
		ISFILTERED('space missions'[Rocket])
		, "All rockets: " & CONCATENATEX(VALUES('space missions'[Rocket]), 'space missions'[Rocket], ", ", 'space missions'[Rocket], ASC)
		, "All rockets"
	)
	
	RETURN yearr & UNICHAR(10) & company & UNICHAR(10) & rocket

EVALUATE
    SUMMARIZECOLUMNS(
        "title_year", [title_year]
		, "selected_filters", [selected_filters]
    )